### ISSUE TITLE
Proje Hakkında

### ISSUE THREAD

**Issue by mhmtcrkglu** [velifiliz/Project#1]
@velifiliz  merhaba,

Paylaşımlarınızı youtube üzerinden takip etmekteyim. Size ulaşabileceğim bir e posta adresi bulamadığım için buradan yazıyorum. Video seriniz devam edecek mi acaba ? 

İyi çalışmalar.

**Comment by karamur** [comment]
merhaba,
"mongodb domain ayarlarında yardımcı olabilirmisiniz. "
